### ISSUE TITLE
App Disconect

### ISSUE THREAD

**Issue by rimedar** [anoop4real/Flutter_MQTT#1]
Hello, im trying you app, but when i try to connect in a second mobile, the first automatically disconnect, can you tell me what is wrong?

**Comment by anoop4real** [comment]
Hi, Its because of the client identifier... for this app I used the clientID hard coded for iOS and Android... in configureAndConnect() method instead of hardcoded osPrefix..  pass a UUID, then it should work. Ideally each client should have a unique identifier. Create a UUID and save it for later use for an app instance.

**Comment by rimedar** [comment]
Yes, thanks, i did, use device_id and it work fine. 
The implementation was so easy.

```
@override
  void initState() {
    super.initState();
    initDeviceID();
}

Future<void> initDeviceID() async {
    deviceID = await DeviceId.getID;
    
    if (!mounted) return;

    setState(() {
      deviceID = deviceID;
    });
  }
```
